# Generated by Django 2.2 on 2024-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
