# Generated by Django 2.2 on 2024-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_auto_20240715_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('sub', models.CharField(max_length=20)),
                ('profs', models.CharField(max_length=10)),
            ],
        ),
    ]
