# Generated by Django 2.2 on 2024-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(unique=True)),
                ('benefits', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='intro',
        ),
    ]
